### ISSUE TITLE
Missing dictionary unpacking in oauth callback function?

### ISSUE THREAD

**Issue by t-karcher** [lucaswerkmeister/cookiecutter-toolforge#3]
Not sure whether this works in the original template, but after adding oauth functionality to my wiki and configuring my (already modified) app to use it, the following error occured:

```
File "...app.py", line 216, in oauth_callback
    request_token = mwoauth.RequestToken(oauth_request_token)
TypeError: __new__() missing 1 required positional argument: 'secret'
```
I fixed this error in my app by unpacking the dictionary in the following function call:

https://github.com/lucaswerkmeister/cookiecutter-toolforge/blob/1577638105b03f0a8ec52768d51c0f3e0b25d71c/%7B%7Bcookiecutter.tool_identifier%7D%7D/app.py#L183

`request_token = mwoauth.RequestToken(**oauth_request_token)`

As I said: I already modified some parts of the template before, and I'm not using a Wikimedia wiki, but this looks like it could also lead to an error in the default setup.

**Comment by lucaswerkmeister** [comment]
Hm, you’re right – looks like I accidentally broke this in 0538548d2f4d55f6362fb2bc237618c5b46c6958. Thanks!
